name: leva_ai
description: "Plataforma para intermediação e contratação de fretes e mudanças. Conecta motoristas e usuários através de busca inteligente por capacidade de carga, tipo de veículo e localização. (Projeto de TCC)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/icons/app_logo.png"